Repository RSC-NA/bot-RSCBot, pull requests merged in 2022-08, with the labels that each got.

#5 Adds DM Helper
  dmHelper/__init__.py
  dmHelper/dmHelper.py
Labels: enhancement

#4 Contract Expiration Refactor
  bulkRoleManager/bulkRoleManager.py
  teamManager/teamManager.py
  transactions/transStringTemplates.py
  transactions/transactions.py
Labels: enhancement, refactor

#7 Fix gm name mismatch?
  teamManager/teamManager.py
  transactions/transactions.py
Labels: bug

#8 Bug quarantine fix
  dmHelper/dmHelper.py
Labels: bug, enhancement

#16 Bringing dmHelper up to snuff again
  dmHelper/dmHelper.py
Labels: bug
